version: '3.8'

services:
  php:
    image: php:8.2-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "8081:80"

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

