[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['npm install']

[start]
cmd = 'npm run start'

[build]
# Command to install PHP dependencies
build_command = "composer install"

[run]
# Command to start PHP-FPM
start_command = "php-fpm -D"